### ISSUE TITLE
Compilation of tutorial.tjp fails due to encoding/special characters

### ISSUE THREAD

**Issue by jwhendy** [taskjuggler/TaskJuggler#105]
I downloaded the tutorial file [here](http://taskjuggler.org/tj3/examples/Tutorial/tutorial.tjp) with:  

```
wget -O test.tjp http://taskjuggler.org/tj3/examples/Tutorial/tutorial.tjp  
```

To compile, I had to fix three errors (compile, get error, fix, repeat). The issues are:
- Line 37: the (c) character in "© 2002 Crappy Software, Inc."
- Line 79: the e+accent in "Sébastien Bono"
- Line 83: the umlaut in "Klaus Müller"

Is this something to do with my system setup/language?

Details:
- Arch Linux x86_64
- tj3 v 3.4.0
- Uncommented lines in /etc/locale.gen
  
  en_US.UTF-8 UTF-8
  en_US ISO-8859-1

Let me know if you need additional information.

If this is a legitimate issue or may affect those without these characters enabled, perhaps they could be replaced with alternative text? 

Thanks,
John

**Comment by thomasw-mitutoyo-ctl** [comment]
Related for Windows: [TaskJugglerInstaller Issue #9](https://github.com/EveryOtherUsernameWasAlreadyTaken/TaskJugglerInstaller/issues/9)

You can use `chcp 65001` before running the Ruby script.
