### ISSUE TITLE
Taskjuggler and system do not agree on current time (affects nowline and "Created by" in gantt html export)

### ISSUE THREAD

**Issue by jwhendy** [taskjuggler/TaskJuggler#156]
Greetings,

Here's a sample minimal file:
```
project nil "test" "1.0" 2014-11-05 +280d {
timingresolution 5min
}

task test "test" {
  task task1 "task1" {
    duration 1h
    start 2014-11-05-08:00
  }
  task task2 "task2" {
    depends !task1
    duration 1h
  }
}

textreport report "Plan" {
  formats html
  header '== test =='

  center -8<-
    [#Plan Plan] | [#Resource_Allocation Resource Allocation]
    ----
    === Plan ===
    <[report id="plan"]>
    ----
   ->8-
}

# A traditional Gantt chart with a project overview.
taskreport plan "" {
  headline "Project Plan"
  columns bsi, name, start, end, duration, chart { scale hour }
  loadunit hours
  hideresource 1
  timeformat "%a %H:%M"
  period 2014-11-05-06:00 + 72h
}
```

Here's my display from the above sample file (note that the "Created on" string at the bottom also suggests it's 6hrs in the future.
![2014-11-05_090519](https://cloud.githubusercontent.com/assets/379357/4919800/47c8fade-64fd-11e4-966f-773504d68389.png)

What my system thinks:
```
$ date
Wed Nov  5 08:56:20 CST 2014
```

Is this a bug or the possible result of an incompatible combination of `timingresolution`, `loadunit`, and/or `columns ... , chart { scale hour }`?

**Comment by jostber** [comment]
Can you remove the timingresolution setting and use the timezone setting instead?

http://www.taskjuggler.org/tj3/manual/timezone.html

**Comment by scrapper** [comment]
TaskJuggler defaults to UTC so projects can be moved between time zones and produce consistent results. You need to use 'timezone' as jostber has pointed out to lock your project into your time zone.
