### ISSUE TITLE
Day length is always 8h

### ISSUE THREAD

**Issue by Xowap** [taskjuggler/TaskJuggler#157]
In my project, I have been setting

```
  workinghours mon - fri 10:00 - 13:00, 14:00 - 18:00
```

Then I have a single task

```
task search "Recherche" {
  effort 1d
  allocate dev
}
```

But if I look too the generated planning, the task will eat up the whole first day, then 1h from the second day. Of course, if I set a 8h working day, it will only plan things in that first day.

Which is a bit annoying, since in France it is required to have 7h work days in most cases.

**Comment by jostber** [comment]
You should be able to use "dailyworkinghours" for this. Set this to 7 hours.

http://www.taskjuggler.org/tj3/manual/dailyworkinghours.html

**Comment by scrapper** [comment]
jostber is correct. Closing the issue.

**Comment by Xowap** [comment]
My bad, thanks!
