### ISSUE TITLE
Printing taskreport Gantt chart problem

### ISSUE THREAD

**Issue by idahogray** [taskjuggler/TaskJuggler#159]
When I print the project's schedule in Gantt chart format, the 2nd page show mostly gray area. See the attachment. This happens on Firefox, I have not tested in Chrome or IE.

![screenclip](https://cloud.githubusercontent.com/assets/1375485/5145077/6a102602-7165-11e4-92be-0c1791833903.png)

**Comment by scrapper** [comment]
We're not using different HTML code for screen and printers. This seems to be a problem with the Firefox print rendering code. I don't think we can do much here on the TaskJuggler side.
