### ISSUE TITLE
Add option to call "resources" "people".

### ISSUE THREAD

**Issue by skorokithakis** [taskjuggler/TaskJuggler#172]
Calling people "resources" is dehumanizing, and viewing schedules made with the otherwise excellent TaskJuggler is a bit painful when it treats people as cogs in the corporate machine. Would it be possible to add an option (or do it outright) to replace the word "resource" with "person"?

I can submit a PR with the change, if necessary, although my Ruby is abysmal.

**Comment by scrapper** [comment]
'resources' can refer to humans as well as machines. As such, I see no issue with this term. Besides that, it's part of the language specification and can't be changed.

**Comment by scrapper** [comment]
You can change column titles if you don't want to show the term in your reports. See http://www.taskjuggler.org/tj3/manual/title.column.html
