### ISSUE TITLE
Online manual shows errors on initial load

### ISSUE THREAD

**Issue by kalafut** [taskjuggler/TaskJuggler#203]
Tried on current versions of Chrome and Safari. Upon first load in a new tab, the documentation index (http://taskjuggler.org/tj3/manual/index.html) displays, but with a big red error box:

> This page contains the following errors:
> 
> error on line 20 at column 16: Extra content at the end of the document
> Below is a rendering of the page up to the first error.

Refreshing the page doesn't help. But if I click on an index link (one of the letters), the error goes away and stays away even through refresh *in that tab*. Open a new tab and the same issue crops up.

**Comment by scrapper** [comment]
Thanks for the hint. It's fixed now.

**Comment by kalafut** [comment]
Thanks!
