### ISSUE TITLE
UTF-8 error 

### ISSUE THREAD

**Issue by bimawa** [taskjuggler/TaskJuggler#212]
Hi guys, help pls with error.
After export Org file to TaskJuggler i'm receive error:
```
org-taskjuggler-compile: TaskJuggler failed with errors: Error: UTF-8 encoding error in line 11:   task                                  "<?><?><?><?><?
```

Taks have a cyrilic symbols, what wrong i do? I'm use org-mode + spacemacs, mac os X, Ruby 2.3 and TaskJuggler v3.6.0

**Comment by jostber** [comment]
Is this only related to the org export or does it happen to all files?

**Comment by bimawa** [comment]
only in org export. Now i use `org-taskjuggler-export` from org mode and `proccess` from terminal.

**Comment by adamfaryna** [comment]
+1
