### ISSUE TITLE
Timesheets division by zero

### ISSUE THREAD

**Issue by felixSchl** [taskjuggler/TaskJuggler#235]
Timesheets for a period less than a week produce division by zero errors.
The problem appears to be that  this function https://github.com/taskjuggler/TaskJuggler/blob/f36b8f44df8ca4c516e1cfd6626e4d9a156760c1/lib/taskjuggler/TimeSheets.rb#L323-L331 would return 0 and it's return value is used as the divisor in a number of places.

**Comment by scrapper** [comment]
The timesheets were designed with a weekly reporting regime in mind. If fixed this particular code now.
