### ISSUE TITLE
Error: Task has not been marked as scheduled.

### ISSUE THREAD

**Issue by thomasw-mitutoyo-ctl** [taskjuggler/TaskJuggler#236]
I have set up a project and I got the error message

> Error: Task xxx has not been marked as scheduled.

I removed almost everything and this is a very small file, which still produces the error:

```
project projectid "Studies"  2019-10-01 - 2022-09-30 {}
resource students "Students" {}

task studies "Studies"{
	allocate students
	task sem6 "Semester 6" {
		start 2019-10-01 
		end 2022-09-30
			task thesis "Thesis" {
				start 2022-06-13
				end 2022-09-05
			}		
	}
}
```
Why can't it schedule the task "studies"? How do I fix it?

It happens with Task Juggler 3.5.0 and 3.6.0

**Comment by jostber** [comment]
Have you set the scheduled keyword somewhere in the project file?

**Comment by thomasw-mitutoyo-ctl** [comment]
> Have you set the scheduled keyword somewhere in the project file?

The above 14 lines are a complete TaskJuggler project. There's no "scheduled" keyword inside. Compile it and it'll give you
```
Error: Task studies has not been marked as scheduled.
```

**Comment by jostber** [comment]
Removing the end date in task "Semester 6" will work: 

`project projectid "Studies"  2019-10-01 - 2022-09-30 {
}

resource students "Students" {
} 

task studies "Studies"{
	allocate students
	task sem6 "Semester 6" {
		start 2019-10-01 
	#	end 2022-09-30
			task thesis "Thesis" {
				start 2022-06-13
				end 2022-09-05
			}		
	}
}
`

**Comment by scrapper** [comment]
Looks like this was an error in the project file and no TJ bug.
