### ISSUE TITLE
Feasibility of creating an online interface?

### ISSUE THREAD

**Issue by fire** [taskjuggler/TaskJuggler#238]
The goal is to create a more accessible interface through the web.

I thought of two approaches: 

* expose an online SQL based interface for the data
* expose an online REST interface to change the data

Afterwards, using these interfaces write a single page application to change the data. Single page applications are the new fashion.

Thoughts?

**Comment by scrapper** [comment]
There have been some attempts but none really gained much ground. But anybody is open to try it again.
