### ISSUE TITLE
Limits (task): limit defined in task works only if smaller than in resource definition

### ISSUE THREAD

**Issue by njkranz** [taskjuggler/TaskJuggler#239]
TaskJuggler version: 3.6.0

Situation: a resource is defined with a capacity of 4 days/week in general. For a specific task, the resource is available 5 days/week. This was modelled in the following way:
1. In the resource definition using "weeklymax 4d":
resource r1 "R1" { limits { weeklymax 4d } }
2. In the task definition using limits { weeklymax 5d { resources r1 } } or just limits { weeklymax 5d } (complete tjp file below)

Expected result: as the manual entry for "Limits (task)" contains an example where the limit is increased in the task relative to the value in the resource definition, the expected result was that a task with an effort of 5d is scheduled with one week (if it starts on a Monday).

Outcome instead: a task with effort 5d extends over two weeks with 4d allocated in the first week and 1d in the second, i.e., the limit remains at 4 d/w. When reducing the limit to 3 d/w in the task, however, the local limit is observed and the tasks extends over two weeks with 3 days allocated in the first week and 2 days in the second week -> lower limits defined in a task are effective but higher limits are not.

Here the tjp test file:
project test "Test" "2020-01-07" 2020-02-01-7:00-+0100 +6m {
	timezone "Europe/Berlin"
	timeformat "%Y-%m-%d"
	numberformat "-" "" "," "." 1
 	currencyformat "(" ")" "," "." 0
	currency "€"
}

resource r1 "R1" { limits { weeklymax 4d } }

task d4 "Weeklymax 4d" {
	start 2020-02-03
	effort 5d
	allocate r1
}

task d5 "Weeklymax 5d" {
	limits { weeklymax 5d { resources r1 } }
	start 2020-02-17
	effort 5d
	allocate r1
}

task d3 "Weeklymax 3d" {
	limits { weeklymax 3d }
	start 2020-03-02
	effort 5d
	allocate r1
}

taskreport "Resources per task" {
  formats csv
  period 2020-02-03 +3m
  timeformat "%F"
  columns bsi, name, resources, effort, weekly
  hidetask (~isactive(plan))
 	sorttasks tree
}

**Comment by scrapper** [comment]
Limits are cumulative. In other words, the lowest limit will limit the allocation. TaskJuggler does not support the specific allocation pattern you are trying to achieve.

**Comment by njkranz** [comment]
Thank you for the fast answer (and for providing TaskJuggler). 

Since the lowest limit counts, may I suggest a small change in the manual? Currently, the manual entry for "Limits (task)" contains an example where the dailymax value for resource R1 is increased from 2 h/d to 4 h/d which is why I considered the different behaviour a bug:

From the manual:
```
resource r1 "R1" {
  # Limit the usage of this resource to a maximum of 2 hours per day,
  # 6 hours per week and 2.5 days per month.
  limits { dailymax 2h weeklymax 6h monthlymax 2.5d }
}

...

task t7 "Task 7" {
  start 2007-06-20
  duration 20d
  allocate r1, r2
  # limits can also be specified per resource
  limits {
    # Limit r1 to half days only
    dailymax 4h { resources r1 }
    # Limit r2 to 6 hours per day
    dailymax 6h { resources r2 }
  }
}
```
