### ISSUE TITLE
Get scheduled per-resource effort of task in reports

### ISSUE THREAD

**Issue by jkrenzer** [taskjuggler/TaskJuggler#241]
Hi!

For the preparation of some contracts it is needed to get the scheduled effort of every resource per every task in a report.

Currently when getting the property effort of a resource which is assigned to a task, there is only the overall effort displayed, not the effort in context of the calling task.

So I propose to add the possibility to query for the scheduled or done effort of a resource per task.

Kind regards,

Jörn

**Comment by jkrenzer** [comment]
After browsing a little through the sources I found that this should happen auto-magically:

https://github.com/taskjuggler/TaskJuggler/blob/133cb022bf368fcde0edd87bbbc100d889f08002/lib/taskjuggler/ResourceScenario.rb#L325-L332

But when calling 

taskreport tasks "Tasks" {
  formats html
  columns bsi, name, resources { listtype bullets listitem "[<-name->] [<-effort->]"}
}

propertyscope always stays empty instead of being set to the current task in the row.

**Comment by jkrenzer** [comment]
The first ! in line 157 seems to conflict with the assignment of the scopeProperty by the "<-query...->" generator: 

https://github.com/taskjuggler/TaskJuggler/blob/133cb022bf368fcde0edd87bbbc100d889f08002/lib/taskjuggler/Query.rb#L156-L164

When using listitem in conjuntion with query or the shortform-generator, @scopeProperty is always nil and @scopePropertyId is set.

But still, after changing this, I can get single task effort but only for manually set scopeproperty with query. So I can still not extract all the information as seems intended.

**Comment by scrapper** [comment]
Can you post a full (but minimal) project example, please? I'm not sure I understand what you are trying to achieve.

**Comment by jkrenzer** [comment]
I created an example to clarify the problem. As mentioned above, it seems to be a bug as the source-code hints the expected result should be generated.

# Example Project File

```taskjuggler

project "Example Project" 2020-07-01 +4m {
}

resource r1 "R1"
resource r2 "R2"
resource r3 "R3"

task t1 "Task1" {
  effort 1d
  allocate r1
  allocate r3
}

task t2 "Task2" {
  effort 2d
  allocate r2
  allocate r3
}

task t3 "Task3" {
  effort 4d
  allocate r1
  allocate r2
  allocate r3
}

taskreport rep1 "Tasks" {
  formats csv
  columns bsi, name, effort, resources { listitem "[<-name->]: [<-effort->]" listtype comma }
}

resourcereport rep2 "Resources" {
  formats csv
  columns bsi, name, effort, duties { listitem "[<-name->]: [<-effort->]" listtype comma }
}
```

# Generated Result

## Tasks.csv

```csv
"BSI";"Name";"Effort";"Resources"
3;"Task3";4.0;"R1: 2.4, R2: 2.4, R3: 2.3"
2;"Task2";2.0;"R3: 2.3, R2: 2.4"
1;"Task1";1.0;"R1: 2.4"
```

## Resources.csv

```csv
"BSI";"Name";"Effort";"Duties"
1;"R1";2.4;"t3, t1"
2;"R2";2.4;"t3, t2"
3;"R3";2.3;"t3, t2"
```


# Expected Result

## Tasks.csv

```csv
"BSI";"Name";"Effort";"Resources"
3;"Task3";4.0;"R1: 1.4, R2: 1.4, R3: 1.3"
2;"Task2";2.0;"R3: 1.0, R2: 1.0"
1;"Task1";1.0;"R1: 1.0"
```

## Resources.csv

```csv
"BSI";"Name";"Effort";"Duties"
1;"R1";2.4;"t3: 1.4, t1: 1.0"
2;"R2";2.4;"t3: 1.4, t2: 1.0"
3;"R3";2.3;"t3: 1.3, t2: 1.0"
```

I could do a PR if it would help.

- Jörn

**Comment by scrapper** [comment]
The 'duties' column does not have support for listitem as stated in the manual. So it's siltently ignored. ;)

But I can see that this would be useful to have. So I've added this feature in the git master.

**Comment by jkrenzer** [comment]
And what about the per resources efforts in the task context? (See Task.csv)

**Comment by scrapper** [comment]
This is fixed as well now!
