### ISSUE TITLE
Replace deprecated Fixnum and Bignum with Integer

### ISSUE THREAD

**Issue by schoettl** [taskjuggler/TaskJuggler#244]
I got
```
TaskJuggler v3.6.0 - A Project Management Software
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
```
 and always get warnings like:

```
/usr/lib/ruby/gems/2.7.0/gems/taskjuggler-3.6.0/lib/taskjuggler/Project.rb:877: warning: constant ::Bignum is deprecated
```

`Bignum` and `Fixnum` are deprecated since ruby version 2.4 and should be replaced with `Integer`.[1]

Are there reasons against this change? I could probably provide a PR.

For me that change would be important: I plan to auto generate reports with a cron job. I only want to receive real error messages via mail :)

[1] https://blog.bigbinary.com/2016/11/18/ruby-2-4-unifies-fixnum-and-bignum-into-integer.html

**Comment by scrapper** [comment]
You can just use TaskJuggler 3.7.1 which works fine with ruby 2.7.

**Comment by schoettl** [comment]
Oh, my fault. I thought TaskJuggler is up-to-date on Arch Linux, but it isn't...

https://aur.archlinux.org/packages/taskjuggler/
