### ISSUE TITLE
wrong project time frame calculation when setting time zones

### ISSUE THREAD

**Issue by geith** [taskjuggler/TaskJuggler#245]
The project time frame calculation seem to be wrong when using time zones. Processing this minimal project fails:
```
project test "Test" 2020-03-01 +12m{
	timezone "Europe/Berlin"
	timeformat "%d.%m.%Y"
}

task t1 "T1" {
	start 2020-03-01
	duration 1m
}
```
The corresponding error message is:
```
test.tjp:7: Error: Date 2020-03-01-00:00-+0100 must be within the project time frame 2020-03-01-01:00-+0100  - 2021-03-01-01:00-+0100
        start 2020-03-01
```
It seems, that the time zone setting is applied twice to the project time frame, the start time is 1AM (`2020-03-01-01:00`), but also with the time zone offset (`+0100`).
Processing this project works, if the `timezone` statement is commented out.

I tested it on TaskJuggler v3.6.0 (Ubuntu 20.04 default installation) but also v3.7.1 (latest Git version, master branch).

**Comment by scrapper** [comment]
As stated in the manual, timezone does not affect the project start and end date. The tjp file is parsed top to bottom and all times before the timezone setting will still inherit the time zone from your environment. But you can specify a time zone for the project start time:

project test "Test" 2020-03-01-00:00:00+0100
