### ISSUE TITLE
Wrong csv output of string with quotes

### ISSUE THREAD

**Issue by abone28** [taskjuggler/TaskJuggler#246]
Checked TaskJuggler version 3.7.1 with following test project:
```
project "csv_test" 2020-07-01 +10d {  now 2020-07-01-08:00 }
task t1 "Task with \"quoted\" word" { duration 1h }
taskreport "report" {  formats csv columns name }
```
TaskJuggler generates following file report.csv
```
"Name"
"Task with "quoted" word"
```
CSV parsers usually expect that quotes in values should be doubled, but TaskTuggler writes them as is.
I think contents of report.csv must be like follows
```
"Name"
"Task with ""quoted"" word"
```

**Comment by scrapper** [comment]
Thanks a lot for the report. This is fixed in the git repo now.
