### ISSUE TITLE
i18n?

### ISSUE THREAD

**Issue by niol** [taskjuggler/TaskJuggler#247]
It is possible to rename columns in reports with translated titles using the `title` attribute. However, there are parts of the reports such as the legend or the _generated on_ footer for which I could not find any way to customize the output. Am I missing something or is TaskJuggler missing some i18n infrastructure? (CLI in English is fine with me but the language the reports are in should be customizable).

**Comment by scrapper** [comment]
TaskJuggler does not have any i18n infrastructure what so ever. I've tried to use intrinsic mechanisms wherever possible. But you call out two areas where a proper i18n support would be the best option. But I have no plans to add this myself. As a workaround, you could post-process the html files with a sed script and replace the few strings you want to have translated. If somebody wants to contribute the i18n infrastructure, I'm certainly open to consider it.
