### ISSUE TITLE
Fatal: undefined method `*' for nil:NilClass 

### ISSUE THREAD

**Issue by spicedreams** [taskjuggler/TaskJuggler#249]
Just getting used to TaskJuggler for a small project...

Started getting this error on "compile" with command
$ rm *.html;  tj3 kbuild.tjp

[error_message.zip](https://github.com/taskjuggler/TaskJuggler/files/5113737/error_message.zip) contains entire project and the error message.

Most recent changes were in task.tji where I was trying to set up simple dependencies between pay_tanks and prep_tanks to deliver_tanks, and sorting out an error like 
./task.tji:14: Error: Task project.prep_tanks has not been marked as scheduled.

System: Linux Mint 18.3 (upstream is Ubuntu 18.04)
$ ruby -v reports ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-linux] with rvm
$ tj3 --version reports tj3 (TaskJuggler) 3.7.1

What I have tried:
checked syntax of charge and chargeset, the latest attributes added.
removed precedes attribute from task prep_tanks which had also a depends attribute
used rvm to downgrade ruby to v2.5.3

None of these has fixed the problem. 

Thanks for looking.

**Comment by spicedreams** [comment]
Perhaps true, but did not help me. 

The two pages of error messages included an explicit statement "You have triggered a bug in TaskJuggler" and instructions how to report the bug. A warning that the project might have incompatible scheduling directives would have been more useful than a crash. 

This project has just 4 tasks other than those from the default template.tjp 

The set of tasks below causes the error (note there is no asap or alap specified). I find I can fix it by nothing more than removing the scheduled attribute from task prep_tanks (discovered by systematic trial and error. I only put it there is response to an earlier warning). It's still unclear how removing the scheduled attribute, which is supposed to take the task outside the scheduling algorithm, would solve a crash in the algorithm.

Thanks for the product, and your help in making it useful. 

task project "KBuild" {
  task  pay_tanks "Pay for Potable Tanks" {
    allocate graham
    milestone
  }
  task    site_plan "Site-Groundworks Plan" {
    allocate oarsom
    milestone
  }
  task    prep_tanks "Prepare for Potable Tanks" {
    depends !site_plan { onend }
    scheduled
    allocate groundwork
  }
  task  deliver_tanks "Receive Potable Tanks" {
    depends !pay_tanks { onend gapduration 8 d }
    chargeset water 100%
    charge 5000 onstart
    start 2020-10-20
  }


/* examples below */

  task  id_template "Name Template" {
  }
  task wp1 "Workpackage 1" {
    task t1 "Task 1"
    task t2 "Task 2"
  }
  task wp2 "Work package 2" {
    depends !wp1
    task t1 "Task 1"
    task t2 "Task 2"
  }
  task deliveries "Deliveries" {
    task "Item 1" {
      depends !!wp1
    }
    task "Item 2" {
      depends !!wp2
    }
  }
/* */
} # ends the outer (project level) task clause

**Comment by scrapper** [comment]
Sorry, I did not realize you had a crash. I'll look into this.

**Comment by scrapper** [comment]
The cash is now fixed in the git repo. Your task project.prep_tanks is overspecified and hence the project cannot be scheduled.

**Comment by spicedreams** [comment]
Thanks
