### ISSUE TITLE
Warning mix of ALAP and ASAP despite no ALAP scheduling

### ISSUE THREAD

**Issue by matclab** [taskjuggler/TaskJuggler#252]
I just have a tjp that produced the following warning after adding a "priority 550" attribute to a task:
```
Warning in scenario plan: Due to a mix of ALAP and ASAP scheduled tasks or a dependency on a lower priority tasks the following task stole resources from plan.task1 despite having a lower priority:
…
```

And thus is despite not using any attribute that (to my knwoledge) set scheduling as ALAP (no `end`, no `depends onend`, no `scheduling alap`,…)

Do you have any clue of what may cause ALAP scheduling ? Are their other attribute that implicitly switch scheduling to ALAP ?

**Comment by scrapper** [comment]
On 2020-11-05 18:46, matclab wrote:
> I just have a tjp that produced the following warning after adding a
> "priority 550" attribute to a task:
> 
> Warning in scenario plan: Due to a mix of ALAP and ASAP scheduled
> tasks or a dependency on a lower priority tasks the following task
> stole resources from plan.task1 despite having a lower priority:
> …
> 
> And thus is despite not using any attribute that (to my knwoledge) set
> scheduling as ALAP (no end, no depends onend, no scheduling alap,…)
> 
> Do you have any clue of what may cause ALAP scheduling ? Are their
> other attribute that implicitly switch scheduling to ALAP ?

Any attribute that will define the end of the task as a fixed date or 
dependency will cause the scheduling direction to be switched to ALAP. 
You are not calling out 'precedes' so that might be it. You can read 
more about it at 
https://taskjuggler.org/tj3/manual/TaskJuggler_Internals.html#How_the_Scheduler_works.

Chris

**Comment by matclab** [comment]
I think I had no `precedes` either.
In the meanwhile I've reworked my planning and the problem disappeared. I 'd still try to reproduce a small example of the problem. I'll come back to report.

**Comment by matclab** [comment]
Closing as I didn't manage to make a small example reproducing the problem
