### ISSUE TITLE
miscalculation (float errors?) when using efficiency

### ISSUE THREAD

**Issue by psi2991** [taskjuggler/TaskJuggler#261]
Hi

the following project demonstrates calculation errors in TaskJuggler v3.7.1
on Ubuntu 20.04.3 LTS
with ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu].
I remember about the same happening with TaskJuggler v3.6.

```
project "Simple Project" 2021-09-09 - 2024-12-31 {
  timingresolution 60min
}

resource team "Team" {
  efficiency 0.78 # holidays: -0.12, overhead: -0.1
  resource r1 "R1"
  resource r2 "R2"
}

task "Task" {
  allocate team
  task "Sub1" {effort 1024h note "expecting 1024h"}
  task "Sub2" {effort 2h note "expecting 2h"}
  task "Sub3" {effort 2d note "expecting 16h"}
}

taskreport breakdown "ProjectBreakdown2" {
  loadunit hours
  formats html, csv
  columns name, effort, note
}

```

output csv is:
```
"Name"    "Effort"  "Note"
"Task"    1042.9    ""
"  Sub1"  1024.1    "expecting 1024h"
"  Sub3"  16.4      "expecting 16h"
"  Sub2"  2.3       "expecting 2h"

```

Solution ideas:
* round every task effort to timingresolution
* add this behaviour to documentation of efficiency

**Comment by scrapper** [comment]
That's not a bug. You have reduced the efficiency of the allocated resources. This will inflate the resulting effort accordingly. You should not use 'efficiency' to handle vacation and other duties. These need to be modeled with the 'vacation' keyword and via real tasks that have high priority and limits.

**Comment by psi2991** [comment]
> You have reduced the efficiency of the allocated resources. This will inflate the resulting effort accordingly.

You mean, it will be off by that factor 1/0.78?
This is not the case:
1024 -> 1310.72
2 -> 2.56
In my csv output, small and large numbers' offsets from expected values (0.1-0.4) have the same order of magnitude.

Thanks for the hints, though.

**Comment by scrapper** [comment]
You also need to factor in that your timing resolution is 60 minutes. So all effort values will be rounded to full hours.
