### ISSUE TITLE
I need a Windows build but this page gives error

### ISSUE THREAD

**Issue by gerroon** [taskjuggler/TaskJuggler#263]
Hi

The main download site says that there is a packaged gem, I do not know what gem is. I just need executables for Windows and Linux. So I go to https://taskjuggler.org/tj3/ and I get

```
404 Not Found
Code: NoSuchKey
Message: The specified key does not exist.
Key: tj3/index.html
RequestId: xxxxx
HostId: xxxxx
An Error Occurred While Attempting to Retrieve a Custom Error Document
Code: NoSuchKey
Message: The specified key does not exist.
Key: error.html
```

thanks

**Comment by l2dy** [comment]
The packaged gem can be downloaded from https://rubygems.org/downloads/taskjuggler-3.7.1.gem, but it's not executable without the Ruby runtime and some dependencies.

You could try using https://github.com/pmq20/ruby-packer to pack it into a single executable.

**Comment by gerroon** [comment]
> The packaged gem can be downloaded from https://rubygems.org/downloads/taskjuggler-3.7.1.gem, but it's not executable without the Ruby runtime and some dependencies.
> 
> You could try using https://github.com/pmq20/ruby-packer to pack it into a single executable.

Thanks, I guess I wont be able to run it here. Are there any plans to make actual Windows builds?

**Comment by scrapper** [comment]
TaskJuggler is written in Ruby. It will always require the Ruby runtime to be installed. But that's available for Windows and many users have successfully installed and used TaskJuggler on Windows.
