### ISSUE TITLE
Timezone more than 12 hours ahead of UTC is rejected

### ISSUE THREAD

**Issue by Conal-Tuohy** [taskjuggler/TaskJuggler#295]
I am working with a project in New Zealand whose time zone is currently 13 hours ahead of UTC, which TaskJuggler rejects. 
I'm going to schedule the project in NZ Standard Time (UTC+12), which will be OK, but TaskJuggler's incorrect assumption should be fixed.

### Error details

My project file begins:
```
project kahikatea "Kahikatea"  2025-01-01-0:00-+1300 +18m {
```
Running `tj3` produces the following output:
```
TaskJuggler v3.7.1 - A Project Management Software

Copyright (c) 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020
              by Chris Schlaeger <cs@taskjuggler.org>

This program is free software; you can redistribute it and/or modify it under
the terms of version 2 of the GNU General Public License as published by the
Free Software Foundation.

kahikatea-project/kahikatea.tjp:6: Error: Time zone adjustment hour out of range (0 - 12) but is 13
project kahikatea "Kahikatea"  2025-01-01-0:00-+1300
```
### Time zone offsets

I've seen this bug before with other software which mistakenly assumes that 12 hours is the maximum offset from UTC. In fact this is not the case, because the international date line is not a straight line that exactly follows the 180° meridian. 

In the north Pacific the date line swings out west of the 180° meridian to avoid some US territories slipping into "tomorrow", although the UTC-1200 time zone is still used in those territories, and UTC-1200 is the most westerly time zone in the world. 

However, in the central and south Pacific, the date line extends significantly east of the 180° meridian, and time zones with offsets greater than +1200 _are_ in fact used, in these areas.

NZ Standard Time is UTC+12 (the antipodes of Greenwich is in NZ waters), but in summer, New Zealand Daylight Savings Time applies, which is 13 hours ahead of UTC. New Zealand's south-eastern archipelago of the Chatham Islands uses its own time zone of UTC+1245 in winter and UTC+1345 in summer. The largest time zone offset actually used anywhere in the world is +14 hours, by the Republic of Kiribati, in the central Pacific.

**Comment by scrapper** [comment]
Thanks for reporting this! I've committed a fix for this issue now. It will be part of the next release.
