### ISSUE TITLE
"Pacific/Auckland" time zone not recognised

### ISSUE THREAD

**Issue by Conal-Tuohy** [taskjuggler/TaskJuggler#296]
Trying to specific a [New Zealand time zone](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#AUCKLAND) using:
```
  # Set the default time zone for the project. 
  timezone "Pacific/Auckland"
```
... produces this error:
```
kahikatea-project/kahikatea.tjp:9: Error: Pacific/Auckland is not a known time zone
```

**Comment by scrapper** [comment]
TaskJuggler relies on the OS system library to resolve time zones. 'Pacific/Auckland' does work for me on a Debian/ChromeOS box. What OS are you using? What version of Ruby?

**Comment by Conal-Tuohy** [comment]
Thanks! That will help with debugging.

I had been running TaskJuggler using this [Docker image](https://github.com/treibholz/docker-taskjuggler) whose Dockerfile looks like this:

```dockerfile
FROM alpine:3.13.2
MAINTAINER Klaus Umbach <klaus+docker@uxix.de>

RUN apk add --no-cache ruby && \
    adduser -u 54123 -g 54123 -D -g tj3 -h /tj3 tj3 

RUN gem install taskjuggler --version 3.7.1 --no-document --clear-sources

VOLUME /tj3
WORKDIR /tj3
USER tj3
```
My host OS does now about `Pacific/Auckland`, but the container may not.

If I run a bash shell inside the container and check the Ruby version, I see: 
```
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux-musl]
```
The docker image seems not have been updated since 2020, so maybe bringing it up to date will help.

**Comment by Conal-Tuohy** [comment]
It turns out that [timezone data are not installed on Alpine Linux](https://github.com/gliderlabs/docker-alpine/issues/136), which is the base image for the docker file I was using.
