### ISSUE TITLE
Can't add project to tj3d

### ISSUE THREAD

**Issue by lamdo** [taskjuggler/TaskJuggler#77]
Hi, 

TaskJuggler seems to perfectly fit my needs, so I gave it a try.
Unfortunately, I'm not able to add any project to tj3d:

user@host:/usr/local/lib/ruby/gems/1.9.1/gems/taskjuggler-3.3.0/examples/Tutorial$ /usr/local/bin/tj3client add tutorial.tjp
TaskJuggler v3.3.0 - A Project Management Software

Copyright (c) 2006, 2007, 2008, 2009, 2010, 2011, 2012
              by Chris Schlaeger chris@linux.com

This program is free software; you can redistribute it and/or modify it under
the terms of version 2 of the GNU General Public License as published by the
Free Software Foundation.

Warning: Projects(s) tutorial.tjp could not be added

The corresponding output of tj3d:
user@host:~$ /usr/local/bin/tj3d -c ~/.taskjugglerrc -d --debug
TaskJuggler v3.3.0 - A Project Management Software

Copyright (c) 2006, 2007, 2008, 2009, 2010, 2011, 2012
              by Chris Schlaeger chris@linux.com

This program is free software; you can redistribute it and/or modify it under
the terms of version 2 of the GNU General Public License as published by the
Free Software Foundation.

Exception `ArgumentError' at /usr/local/lib/ruby/1.9.1/psych/scalar_scanner.rb:91 - invalid value for Integer(): "global"
Exception`DRb::DRbConnError' at /usr/local/lib/ruby/1.9.1/drb/drb.rb:570 - connection closed
Warning: Loading of project failed: connection closed
Exception `DRb::DRbConnError' at /usr/local/lib/ruby/1.9.1/drb/drb.rb:570 - connection closed

There is only one line in tj3d.log: 
2012-08-14 16:59:36 warning tj3d[7199]: Loading of project failed: connection closed

I'm running Ubuntu 12.04. As it didn't work out with the stock ruby 1.9.3, I tried compiling the latest ruby version from source. The output included above has been produced with vanilla ruby.

I hope that this information is enough to get you an idea what is going wrong :-)

**Comment by deepfire** [comment]
This could have been related to #168 as well as #161.
@scrapper, is there any chance a new release with a fix for this can be made?
