### ISSUE TITLE
Include *prefixes lost for multiple sub-includes.

### ISSUE THREAD

**Issue by jmglogow** [taskjuggler/TaskJuggler#80]
I have a project, which includes a generated tji, which itself includes multiple generated tjis. I've attached a minimal example. The broken version complains about an unknown task.

I've added debugging output to the "pushFileStack" and "popFileStack"  and I can see that the prefix is not pushed for the first include (sup2.tji). I guess it's because of the "include macro before project without prefix" rule, but I couldn't find the real error and fix within some time and there is a workaround by including a dummy.tji before all other includes... so here is the bug report.

inc.tjp:

```
project p1 "Steal Project" 2012-08-23 +1w {
}

resource dev1 "Dev1"

task main "Main" {
  task t1 "T1"
}

include "sup1.tji" { taskprefix main }
```

sup1.tji:

```
# Error - pops @fileStack
include "sup2.tji"

# Ok
include "sup3.tji" { taskprefix main }

# Broken
include "sup3.tji"
```

sup2.tji:

```
supplement task t1 {
  effort 1d
}
```

sup3.tji:

```
supplement task t1 {
  allocate dev1
}
```

**Comment by arturog** [comment]
Hi All, I think I got this bug as well -the taskprefix is being lost for the first include.
@scrapper : Can you share the fix you did?  Perhaps this is a regression.  Cheers.
